export default {
  background: 'background',
  navbar: 'navbar',
  navbarAnimation: 'navbar-animation',
  home: 'home',
  homeAnimation: 'home-animation',
  button: 'button',
  arrow: 'arrow',
  arrowContainer: 'arrow-container',
  projectTileImg: 'project-tile-img',
  projectTileTitle: 'project-tile-title',
  projectTile: 'project-tile',
  projects: 'projects',
  link: 'link',
  tileInfo: 'tile-info',
  title: 'title',
  projectTitle: 'project-title',
  projectImage: 'project-image',
  projectDesc: 'project-desc',
  projectButtons: 'project-buttons',
  projectButton: 'project-button',
  contactImage: 'contact-image',
  contactPiece: 'contact-piece',
  contactPieces: 'contact-pieces',
};
